#!/bin/bash

make learnopt || exit

d=64test
outd="$d/output"
cord="$d/correct"
mkdir -p $outd

doTest() {
  if [ "$1" == "-s" ]; then
    ./learnopt -tr "$d/${3}${2}.imap" -dotf "${outd}/${3}${2}.dot" >& /dev/null 
    echo "diff ${3}${2}.dot"
    diff  "$outd/${3}${2}.dot" "$cord/${3}${2}.dot"
  else
    grep ';' "$d/${3}${2}_cross.imap" | sed -e '1,$s/;/;\n/g' | grep '.' \
        | awk '{ print ".L0x0000000000003758",$0; }' >& /tmp/zqasm
    grep -v ';' "$d/${3}${2}_cross.imap" > /tmp/zqrtl
    ./learnopt -r /tmp/zqrtl -o /tmp/zqrtl.rtl
    ./learnopt -tr "$d/${3}${2}.imap" -l /tmp/zqasm -o /tmp/zqasm.lift.rtl >& /dev/null
    echo "generate ${3}${2}_cross.log"
    diff /tmp/zqrtl.rtl /tmp/zqasm.lift.rtl >& "$outd/${3}${2}_cross.log"
  fi
}


echo "Testing stability of learning process..."
for f in 1 2 3 4 5 6 7 8 9 10 10a 11; do
    doTest "-s" "$f" strain
done


echo "Testing ability to generalize in case of different opcode's suffix..."
for f in 1 2 3 4 5; do
    doTest "-d" "$f" train
done

