#!/bin/bash
if [ $# -eq 0 ]; then
	echo 'Input file not specified, exiting' && exit 1
fi

if [ $# -eq 1 ]; then
	m=1
elif [ "$2" == "off" ]; then
	m=0
elif [ "$2" == "on" ]; then
	m=1
fi

grep ';' "$1" | sed -e '1,$s/;/;\n/g' | grep '.' | awk '{ print ".L0x0000000000003758",$0; }' > /tmp/zqasm
grep -v ';' "$1" > /tmp/zqrtl
make learnopt
./learnopt -r /tmp/zqrtl -o /tmp/zqrtl.rtl
./learnopt -tr "$1" -l /tmp/zqasm -o /tmp/zqasm.lift.rtl
if [ mode == 0 ]; then
	sed -i -E "s/mode:[0-9a-zA-Z]+/mode/g" /tmp/zqasm.lift.rtl
	sed -i -E "s/mode:[0-9a-zA-Z]+/mode/g" /tmp/zqrtl.rtl
fi
cut -f2- /tmp/zqasm | paste -d"#" - /tmp/zqrtl.rtl > /tmp/zq1.pair
cut -f2- /tmp/zqasm | paste -d"#" - /tmp/zqasm.lift.rtl > /tmp/zq2.pair
diff -w /tmp/zq1.pair /tmp/zq2.pair
