#include "libutils.h"

using namespace std;
unordered_map <uint64_t, string> utils::sym_bindings;
set <string> utils::cf_ins_set {
   "jb",
   "jnae",
   "jc",
   "jbe",
   "jna",
   "jrcxz",
   "jl",
   "jnge",
   "jle",
   "jng",
   "jmp",
   "jmpe",
   "jmpf",
   "jnb",
   "jae",
   "jnc",
   "jnbe",
   "ja",
   "jnl",
   "jge",
   "jnle",
   "jg",
   "jno",
   "jnp",
   "jpo",
   "jns",
   "jnz",
   "jne",
   "jo",
   "jp",
   "jpe",
   "js",
   "jz",
   "je",
   "loop",
   "loopnz",
   "loopne",
   "loopz",
   "loope",
   "call",
   "callf",
   "callq",
   "jmpq",
   "ret",
   "retq" };


set <string> utils::uncond_cf_ins_set {
  "jmp",
  "call",
  "callq",
  "jmpq",
  "retq",
  "ret",
  "jmpq"
};
unordered_map <uint8_t,string> utils::prefixes {
  {0x40,"rex"     },
  {0x40,"rexq"    },
  {0x40,"rexz"    },
  {0x41,"rex.B"   },
  {0x42,"rex.X"   },
  {0x43,"rex.XB"  },
  {0x44,"rex.R"   },
  {0x45,"rex.RB"  },
  {0x46,"rex.RX"  },
  {0x47,"rex.RXB" },
  {0x48,"rex.W"   },
  {0x49,"rex.WB"  },
  {0x4a,"rex.WX"  },
  {0x4b,"rex.WXB" },
  {0x4c,"rex.WR"  },
  {0x4d,"rex.WRB" },
  {0x4e,"rex.WRX" },
  {0x4f,"rex.WRXB"},
  {0xf3,"rep"     },
  {0xf3,"repz"    },
  {0xf3,"repq"    },
  {0x3e,"notrack" },
  {0xf0,"lock"    },
  {0xf2,"repnz"   },
  {0xf2,"repne"   },
  {0x2e,"ss"      },
  {0x26,"es"      },
  {0x64,"fs"      },
  {0x65,"gs"      },
  {0x2e,"cs"      },
  {0x3e,"ds"      }
};

unordered_set <string> utils::prefix_ops {
  {"rex"     },
  {"rexq"    },
  {"rexz"    },
  {"rex.B"   },
  {"rex.X"   },
  {"rex.XB"  },
  {"rex.R"   },
  {"rex.RB"  },
  {"rex.RX"  },
  {"rex.RXB" },
  {"rex.W"   },
  {"rex.WB"  },
  {"rex.WX"  },
  {"rex.WXB" },
  {"rex.WR"  },
  {"rex.WRB" },
  {"rex.WRX" },
  {"rex.WRXB"},
  {"rep"     },
  {"repz"    },
  {"repq"    },
  {"notrack" },
  {"lock"    },
  {"repnz"   },
  {"repne"   },
  {"ss"      },
  {"es"      },
  {"fs"      },
  {"gs"      },
  {"cs"      },
  {"ds"      }
};
unordered_set <string> utils::invalid_prefixes {
  "ss",
  "es",
  "fs",
  "gs",
  "cs",
  "ds"
};

unordered_set <string> utils::ctrl_regs {
  "%cr0",
  "%cr1",
  "%cr2",
  "%cr3",
  "%cr4"
};
unordered_set <string> utils::debug_reg {
    "%dr0",
    "%dr1",
    "%dr2",
    "%dr3",
    "%dr4",
    "%dr5",
    "%dr6",
    "%dr7"
};
unordered_set <string> utils::priviledge_ins {
  "lgdt",
  "lldt",
  "ltr",
  "lmsw",
  "clts",
  "invd",
  "invlpg",
  "wbinvd",
  "rdmsr",
  "wrmsr",
  "rdpmc",
  "rdtsc"
};
